# Generated by Django 5.0.4 on 2024-04-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='secret',
            field=models.CharField(default=15, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
