# Generated by Django 5.0.4 on 2024-04-27 22:22

import poseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0005_alter_apikey_user_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='expires',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(default=poseapp.models.get_default_scopes),
        ),
    ]
