# Generated by Django 5.0.4 on 2024-04-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poseapp', '0006_alter_apikey_expires_alter_apikey_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='gender',
            field=models.CharField(default='male', max_length=100),
        ),
    ]
